name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Deploy
        uses: jekyll/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
          token: ${{ secrets.GITHUB_TOKEN }}
